[workspace]
authors = ["84176052+sounddrill31 <84176052+sounddrill31@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "data-forms-website"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]
prep_yaml = "python generate_teams.py"
generate = "python generate_site.py"
download = "python downloader.py"
prepare = "pixi run download && pixi run prep_yaml && pixi run generate"
start = "pixi run prepare && echo 'Open http://localhost:8000 to see the web page!' && python -m 'http.server' 8000 -d 'output'"
ci = "python ci.py"

[dependencies]
python = ">=3.13.5,<3.14"
pyyaml = ">=6.0.2,<7"
requests = ">=2.32.5,<3"
pillow = ">=11.3.0,<12"

[pypi-dependencies]
pillow-jxl-plugin = ">=1.3.4, <2"
